version: "3.9"

services:
  db:
    container_name: movieapp_db
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
